<a href="https://colab.research.google.com/github/Anakha-s/Data-Science/blob/main/Experiment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrices Addition

In [ ]:
X=[[1,1,1],[2,2,2],[3,3,3]]
Y=[[1,1,1],[1,1,1],[1,1,1]]
R=[[0,0,0],[0,0,0],[0,0,0]]
for i in range(len(X)):
  for j in range(len(X[0])):
    R[i][j]=X[i][j]+Y[i][j]
for r in R:
  print(r)

[2, 2, 2]
[3, 3, 3]
[4, 4, 4]


Matrices Subtraction

In [ ]:
X=[[1,1,1],[2,2,2],[3,3,3]]
Y=[[1,1,1],[1,1,1],[1,1,1]]
R=[[0,0,0],[0,0,0],[0,0,0]]
for i in range(len(X)):
  for j in range(len(X[0])):
    R[i][j]=X[i][j]-Y[i][j]
for r in R:
  print(r)


[0, 0, 0]
[1, 1, 1]
[2, 2, 2]


sum of an array

In [1]:
import numpy as np 
       
# 1D array 
arr = [20, 2, 2, 10, 4]  
   
print("\nSum of 1D array : ", np.sum(arr))

# 2D array 

arr2 = [[14, 17, 12, 33, 44],   
       [15, 6, 27, 8, 19],  
       [23, 2, 54, 1, 4,]]  
   
print("\nSum of 1D array : ", np.sum(arr2)) 
   





Sum of 1D array :  38

Sum of 1D array :  279


Matrix dot product

In [ ]:
import numpy as np
 

a = [[1, 1], 
     [2, 2]]
     
b = [[1, 1],
     [3, 3]]
 

print(np.dot(b, a))

[[3 3]
 [9 9]]


In [2]:
#element-wise Multiplication
import numpy as np

a1 = np.array([[12,46,23,7,2],[3,5,8,3,6]])
a2 = np.array([[15,26,2,17,22],[13,8,9,3,4]])

print(np.multiply(a1,a2))

[[ 180 1196   46  119   44]
 [  39   40   72    9   24]]


In [4]:
#transpose
import numpy as np
Ms=np.matrix('[4,1 ; 12,3]')
Tr=Ms.transpose()
print(Tr)

[[ 4 12]
 [ 1  3]]


In [23]:
#SVD
import numpy as np
A=np.array([[3,4,3],[1,2,3],[4,2,1]])
U,D,VT=np.linalg.svd(A)
A_ans = (U @ np.diag(D) @ VT)
print(U)
print()
print(D)
print()
print(VT)
print()
print(A_ans)

[[-0.73553325 -0.18392937 -0.65204358]
 [-0.42657919 -0.62196982  0.65664582]
 [-0.52632788  0.76113306  0.37901904]]

[7.87764972 2.54031671 0.69958986]

[[-0.60151068 -0.61540527 -0.5093734 ]
 [ 0.73643349 -0.18005275 -0.65210944]
 [ 0.30959751 -0.76737042  0.5615087 ]]

[[3. 4. 3.]
 [1. 2. 3.]
 [4. 2. 1.]]
